name: SoulLink
version: '${project.version}'
main: soullink.soullink.SoulLink
api-version: '1.20'
author: WizarTheGreat
commands:
  link:
    description: Lets you link players together.
                  Requires two players to link.
    usage: /link
    permission: isOP
  unlink:
    description: Lets you unlink players
                  Requires two players to link.
    usage: /unlink
    permission: isOP
  linkinfo:
    description: Lets you check who someone is linked to.
    usage: /linkinfo
  setlinklevel:
    description: Let's you set how many "kills" a person has, 
        and therefore how far they are from freedom.
    usage: /setlinklevel
    permission: isOP
