#Link choices
  #How many deaths before a ban
Death Limit: 5
  #How many kills they need to get to be freed
Kills to freedom: 4
  #How many kills to unlink levels
Kills to xp: 1
  #How many kills to unlink potion effects
Kills to potion: 2
  #How many kills to unlink inventories
Kills to inventory: 3
    #Made by WizarTheGreat
